### ISSUE TITLE
tensorflow not available in cosmodesi env

### ISSUE THREAD

**Issue by erikzaborowski** [cosmodesi/desilike#23]
Hi, I was unable to train a neural emulator (MLPEmulatorEngine) in the NERSC cosmodesi environment because it appears tensorflow is not installed.

This is not pressing for me, but I wanted to alert to the issue.

**Comment by adematti** [comment]
tensorflow is now in the cosmodesi environment at NERSC, please let me know if you face issues (https://github.com/cosmodesi/cosmodesiconda would be the best place to raise environment-related issues).

**Comment by erikzaborowski** [comment]
Thank you Arnaud - and noted, regarding the cosmodesiconda repo.
