### ISSUE TITLE
Error when reading in window matrix from filepath

### ISSUE THREAD

**Issue by erikzaborowski** [cosmodesi/desilike#24]
Hello, I’m getting an error when feeding a window filepath (.npy) into a desilike observable, using this code as an example: https://github.com/cosmodesi/desi-y1-kp7/blob/main/mock_challenge_y1/fits_2pt.py#L211. I am using the standard cosmodesi environment at NERSC.

The error itself is shown below, and I have created a ~minimal example reproducing the error in this notebook at NERSC: `/global/cfs/cdirs/desi/users/ezaborow/window_min_example.ipynb`.

Thanks a lot for any help!

![window_error](https://github.com/cosmodesi/desilike/assets/28712568/673b93f9-4fa8-4a95-82cd-60d0fce11566)

**Comment by adematti** [comment]
Thanks Erik, should be fixed now.
Just in case, in your example it's easier to just leave desilike deal with the pypower files and rebinning:
```
theory = LPTVelocileptorsTracerPowerSpectrumMultipoles()
observable = TracerPowerSpectrumMultipolesObservable(
    data=all_mocks[ix_dat],
    covariance=[mock for imock, mock in enumerate(all_mocks) if imock != ix_dat],
    wmatrix=wmatrix_path,
    theory=theory, klim={ell: (kmin, kmax, 0.005) for ell in ells}, kinlim=(0.001, 0.3))

# Call likelihood

likelihood = ObservablesGaussianLikelihood(observable)
likelihood()
```
kinlim[0] should be > 0. to avoid overflows in velocileptors.
(also, about the number of mocks for the covariance matrix --- we now have 1000 EZ mocks)

**Comment by erikzaborowski** [comment]
Thanks for getting to this so quick Arnaud! And the tips are very helpful.
