### ISSUE TITLE
Automatic inference of Percival 2014 factor

### ISSUE THREAD

**Issue by zhaoruiyang98** [cosmodesi/desilike#35]
Hi!

I found sometimes the automatic inference of Percival 2014 factor is incorrect. For example, if I change cell 2 in the [example notebook](https://github.com/cosmodesi/desilike/blob/hmc/nb/fs_direct_examples.ipynb) to

```python
from desilike.theories.galaxy_clustering import DirectPowerSpectrumTemplate, KaiserTracerPowerSpectrumMultipoles
from desilike.theories.primordial_cosmology import Cosmoprimo
from desilike.observables.galaxy_clustering import TracerPowerSpectrumMultipolesObservable
from desilike.likelihoods import ObservablesGaussianLikelihood
from desilike.parameter import ParameterCollection
from desilike import setup_logging


cosmo = Cosmoprimo(fiducial="DESI")
cosmo.init.params["sigma8_m"] = {"derived": True, "fixed": False, "latex": R"\sigma_8"}
cosmo.init.params["omega_cdm"].update(derived="0.26 * {h}**2")
for param in ['omega_b', 'n_s', 'tau_reio']: cosmo.params[param].update(fixed=True)
template = DirectPowerSpectrumTemplate(z=z, cosmo=cosmo)
theory = KaiserTracerPowerSpectrumMultipoles(template=template)
theory.params['b1'].update(value=2.)
observable = TracerPowerSpectrumMultipolesObservable(data=data, covariance=mocks,
                                                     klim={0: [0.02, 0.2], 2: [0.02, 0.2]}, # fit monopole and quadrupole, between 0.02 and 0.2 h/Mpc
                                                     theory=theory)
likelihood = ObservablesGaussianLikelihood(observables=[observable])

setup_logging()
likelihood()
```
, where I've added one derived parameter `sigma8_m` (I guess it makes more sense to explicitly set `fixed=False` here because `sigma8_m` is not a fixed derived parameter? The default behaviour is `fixed=True`) and one constraint `Omega_cdm=0.26` as an example. The output shows `Covariance matrix with 36 points built from 999 observations, varying 6 parameters`, while actually there're only 4 free parameters.

This could be fixed by changing [this line](https://github.com/cosmodesi/desilike/blob/ab360aa3427a1e9c1bc12c36f40f17fe7a70767b/desilike/likelihoods/base.py#L504) of code to
```python
for obs in self.observables: params |= set(obs.all_params.names(varied=True, input=True))
nparams = len(params)
self.percival2014_factor = (1 + B * (nbins - nparams)) / (1 + A + B * (nparams + 1))
if self.mpicomm.rank == 0:
    self.log_info('Covariance matrix with {:d} points built from {:d} observations, varying {:d} parameters: {}.'.format(nbins, self.nobs, nparams, params))
    self.log_info('...resulting in a Percival 2014 factor of {:.4f}.'.format(self.percival2014_factor))
```
, but if I apply the constraint at the likelihood level `likelihood.all_params["omega_cdm"].update(derived="0.26 * {h}**2")`, it is still not correct. Then I'm not sure how to fix it, but hopefully logging the varied parameters names should be enough to make people aware of the issue?

**Comment by adematti** [comment]
good catch, thanks! I'll propose something

**Comment by adematti** [comment]
thanks! should be fixed by 20b51014053a2e524db1446d00b81ae4817bbe6e

**Comment by zhaoruiyang98** [comment]
Thank you Arnaud!

**Comment by zhaoruiyang98** [comment]
Hi Arnaud! When I run joint fit w/o emulators (different direct fit templates share the same`Cosmoprimo` object), some cosmological parameters seem double-counted, i.e., `params` here contains duplicated cosmological parameters, and the Percival factor reported is incorrect.
https://github.com/cosmodesi/desilike/blob/11ed8ec28824bf6f768326b6310715ef643ec221/desilike/likelihoods/base.py#L575

Maybe I didn't use desilike in a proper way, but it seems to be fixed by adding the following code to filter out unique `Parameter` based on its name.
```python
seen = {}
for param in params:
    if param.name not in seen:
        seen[param.name] = param
params = list(seen.values())
```

**Comment by zhaoruiyang98** [comment]
The latest commit fixed this issue. Thanks!
