### ISSUE TITLE
Calling for varied_params in Planck likelihood changes parameter value?!

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/desilike#7]
(not just in likelihood, but in cosmo you sent to it on setup)

from desilike.likelihoods.cmb import TTTEEEHighlPlanck2018PlikLiteLikelihood

from desilike.theories.primordial_cosmology import Cosmoprimo

Planckavg={"h":0.6736,"omega_cdm":0.1200,"omega_b":0.02237,"logA":3.044,"n_s":0.9649,
                             "tau_reio":0.0544}

cosmo = Cosmoprimo()

for key,val in Planckavg.items(): cosmo.varied_params[key].update(value=val)

print(cosmo.varied_params['logA'].value)

testL=TTTEEEHighlPlanck2018PlikLiteLikelihood(cosmo=cosmo)

print(cosmo.varied_params['logA'].value)
#3.044
testL.varied_params
print("This changes value of logA?!")

print(cosmo.varied_params['logA'].value)
#3.036
print(testL.varied_params['logA'].value)

**Comment by adematti** [comment]
Sorry, what objects "living outside your framework" are you refering to? what do you think, even just for debugging, is helpful?
I don't think we want to copy cosmo, because we want the same instance to be used in e.g. all Planck likelihoods.
To me it's more about "lack of documentation". Have you gone through all notebooks? (especially https://github.com/cosmodesi/desilike/blob/main/nb/basic_examples.ipynb).

**Comment by adematti** [comment]
but to answer what you wanted to do original, wouldn't:
`cosmo = Cosmoprimo()
likelihood = TTTEEEHighlPlanck2018PlikLiteLikelihood(cosmo=cosmo)
for m_ncdm in np.linspace(0., 0.1, 10): print(m_ncdm, likelihood(m_ncdm))`
work?

**Comment by pmcdonal** [comment]
The m_ncdm loop, yes, if I knew to do that it would have been exactly what I wanted, and very straightforward...
But I read fisher_planck.ipynb first and saw things like this... 
for param in likelihood_clik.all_params.select(name=['w0_fld']):
    param.update(fixed=False)
so I guess I got the idea you changed parameters with update. I was pleased with myself for having simplified parameter setting relative to this "select" loop, so... this is the context for saying it is hard for a human to use 🙂
